# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RestaurantSearch' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RestaurantSearch

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'RestaurantSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
